### ISSUE TITLE
Using hierarchy with flow 

### ISSUE THREAD

**Issue by agramms** [serradura/u-case#19] opened 2020-05-01 14:10 UTC
When I use a class that inherit from a class that use Micro::Case with a flow defined, this class have a different behavior from expected.

First, i have to define the same flow that is defined in top level class, the flow was not called if it isn't declared in leaf class.

*Top Level Class*:

![Pasted_Image_01_05_20_11_01](https://user-images.githubusercontent.com/79534/80810959-4ca07f80-8b9b-11ea-82b0-489090efb5b8.png)

*Leaf one*:

![Pasted_Image_01_05_20_10_50](https://user-images.githubusercontent.com/79534/80810672-b9ffe080-8b9a-11ea-89b7-74a4302ea94c.png)

But even with that, in the tests it some times call the leaf call! class, and others from the inherited class. I'm using rspec for the tests.

If I call only one test, the result is ok:

![image](https://user-images.githubusercontent.com/79534/80811161-b587f780-8b9b-11ea-8d89-99f7ce2fbf88.png)

but when I run all the tests, the Success response is from the inherited calls, not from the other one:

![image](https://user-images.githubusercontent.com/79534/80811259-e536ff80-8b9b-11ea-93db-e644a488cada.png)

I think that it can be a unexpected way of using flow.
I'm using flow in the right way?

Let me know if you need any additional information.

Thanks!

**Comment by serradura** [comment] 2020-05-01 14:51
Hi @agramms, thank you for reporting this issue.

As you said, I think that is a bug. I'll fix it and ensure that the usage of inheritance of classes which has an inner flow works as expected. But, I would like to recommend the usage of composition over inheritance, in this case, you could duplicate the flow declaration in both classes, or create a common flow to be the first step of these classes to avoid inheritance.

**Comment by serradura** [comment] 2020-05-02 03:12
Hi @agramms, I thought about your issue and the root cause of it hurts one of the goals of this project. (Solve complex business logic, by **allowing the composition of use cases**.).

So, because of this, I won't fix it. But, I'll add a new feature that will raise an exception if somebody tries to inherit from a use case that has an inner flow.

**Closed by serradura** 2020-05-02 03:12 UTC
Labels: wontfix
